### ISSUE TITLE
Add support for `cosmwasm_std::Response<T>` with non-empty response trait

### ISSUE THREAD

**Issue by foxpy** [AbstractSDK/cw-orchestrator#143]
Default type used for `Response` is `cosmwasm_std::Response<cosmwasm_std::Empty>` which is fine in most situations.

However, attempt to use custom trait type with `cw_orch::interface_entry_point` results in compilation error:
```
error[E0308]: mismatched types
  --> src/contract.rs:16:1
   |
16 | #[cfg_attr(feature = "interface", cw_orch::interface_entry_point)]
   | ^
   | |
   | expected struct `Empty`, found enum `NeutronMsg`
   | expected `Result<cosmwasm_std::Response, cw_orch::anyhow::Error>` because of return type
   |
   = note: expected enum `Result<cosmwasm_std::Response<cosmwasm_std::Empty>, _>`
              found enum `Result<cosmwasm_std::Response<NeutronMsg>, _>`
   = note: this error originates in the attribute macro `cw_orch::interface_entry_point` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Example to reproduce

```rust
#[cfg_attr(not(feature = "library"), cosmwasm_std::entry_point)]
#[cfg_attr(feature = "interface", cw_orch::interface_entry_point)]
pub fn instantiate(
    _deps: DepsMut,
    _env: Env,
    _info: MessageInfo,
    _msg: InstantiateMsg,
) -> ContractResult<Response<neutron_sdk::bindings::msg::NeutronMsg>> { Ok(Response::new()) }
```

Note: this example depends on https://crates.io/crates/neutron-sdk

**Comment by Kayanski** [comment]
The issue here is that we need to coerce the type of the instantiate function (and other endpoints actually), to be able implement the Contract trait on a struct : https://github.com/CosmWasm/cw-multi-test/blob/9d000f6a028912e8bfb6279627bc7d14d41e5566/src/contracts.rs#L15.

In order to do that, we need to be able to get the generic type of the cosmwasm_std::Response struct.
(For instance here, we need to be able to get the tokens `neutron_sdk::bindings::msg::NeutronMsg` from the return type of the instantiate function).

This is however not always possible. I propose a fix that is not optimal : 

1. We try to parse the first generic of the return type of the endpoint function (here Response). We then proceed to match the first generics of this type (here `neutron_sdk::bindings::msg::NeutronMsg`)
2. If this doesn't work, we fallback to Empty.

What helps us in this situation though is that the Response Generics has to be the same for all enpoints

**Comment by CyberHoward** [comment]
How about skipping the `Contract` implementation if the custom response type is not `Empty`?

**Comment by foxpy** [comment]
@CyberHoward should we close this issue now?
